#!/usr/bin/env bash
set -e
exit_code=0
# Format Terraform and Terragrunt files
# This will format all staged files that match *.tf, *.tfvars, or terragrunt.hcl patterns.

# Do we have terraform and terragrunt installed?
if ! command -v terraform >/dev/null || ! command -v terragrunt >/dev/null; then
    echo "Both terraform and terragrunt must be both installed." >&2
    exit 1
fi

for file in $(git diff --cached --name-only --diff-filter=ACM | grep -E '(\.tf$|\.tfvars$|terragrunt\.hcl$)'); do
    if [[ "$file" == *.tf || "$file" == *.tfvars ]]; then
        terraform fmt "$file" || exit_code=1
    elif [[ "$file" == *terragrunt.hcl ]]; then
        terragrunt hclfmt "$file" || exit_code=1
    fi
done

# Update/generate Terraform docs

# Find all staged TF, TFVARS, HCL file changes
service_dirs=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^env/.+\.tf$|^env/.+\.tfvars$' | xargs -n1 dirname)
# Check if terraform-docs is installed
if command -v terraform-docs >/dev/null; then
    for dir in $service_dirs; do
        # Case insensitive check for README.md
        readme=$(find "$dir" -maxdepth 1 -iname readme.md)
        for file in $readme; do
            # Check if README.md is a symlink to a module folder's README.md
            if [[ -L "$readme" ]]; then
                real_readme=$(realpath "$readme")
                module_dir=$(dirname "$real_readme")
                echo "Service README is a symlink, updating module's README.md at $real_readme"
                # compgen -G "$dir/*.tf" checks for existence of any Terraform (*.tf) files in $dir
                if compgen -G "$module_dir/*.tf" > /dev/null; then
                    (cd "$module_dir" && terraform-docs markdown --output-file "$(basename "$readme")" --output-mode inject .) || exit_code=1
                fi
                continue
            fi
            # Otherwise update the service folder's README.md
            if compgen -G "$dir/*.tf" > /dev/null; then
                echo "Updating Terraform docs in $dir/README.md"
                (cd "$dir" && terraform-docs markdown --output-file "$(basename "$readme")" --output-mode inject .) || exit_code=1
            fi
        done
    done

    # Find all staged module folder's TF file changes
    module_dirs=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^modules/.+\.tf$' | xargs -n1 dirname) 
    for dir in $module_dirs; do
        readme=$(find "$dir" -maxdepth 1 -iname readme.md)
        for file in $readme; do
            # compgen -G "$dir/*.tf" checks for existence of any Terraform (*.tf) files in $dir
            if compgen -G "$dir/*.tf" > /dev/null; then
                echo "Updating Terraform docs in Module $dir/README.md"
                (cd "$dir" && terraform-docs markdown --output-file "$(basename "$readme")" --output-mode inject .) || exit_code=1
            fi
        done
    done
fi

exit $exit_code